package com.example.climatepulse

object Locations {

val capitalCities = listOf(

    "Belarus" to "Minsk",
    "Belgium" to "Brussels",
    "Belize" to "Belmopan",
    "Benin" to "Porto-Novo",
    "Bhutan" to "Thimphu",
    "Bolivia" to "Sucre",
    "Bosnia and Herzegovina" to "Sarajevo",
    "Botswana" to "Gaborone",
    "Brazil" to "Brasília",
    "Brunei" to "Bandar Seri Begawan",
    "Bulgaria" to "Sofia",
    "Burkina Faso" to "Ouagadougou",
    "Burundi" to "Gitega",
    "Cabo Verde" to "Praia",
    "Cambodia" to "Phnom Penh",
    "Cameroon" to "Yaoundé",
    "Canada" to "Ottawa",
    "Central African Republic" to "Bangui",
    "Chad" to "N'Djamena",
    "Chile" to "Santiago",
    "China" to "Beijing",
    "Colombia" to "Bogotá",
    "Comoros" to "Moroni",
    "Congo (Congo-Brazzaville)" to "Brazzaville",
    "Costa Rica" to "San José",
    "Croatia" to "Zagreb",
    "Cuba" to "Havana",
    "Cyprus" to "Nicosia",
    "Czechia (Czech Republic)" to "Prague",
    "Denmark" to "Copenhagen",
    "Djibouti" to "Djibouti",
    "Dominica" to "Roseau",
    "Dominican Republic" to "Santo Domingo",
    "Ecuador" to "Quito",
    "Egypt" to "Cairo",
    "El Salvador" to "San Salvador",
    "Equatorial Guinea" to "Malabo",
    "Eritrea" to "Asmara",
    "Estonia" to "Tallinn",
    "Eswatini" to "Mbabane",
    "Ethiopia" to "Addis Ababa",
    "Fiji" to "Suva",
    "Finland" to "Helsinki",
    "France" to "Paris",
    "Gabon" to "Libreville",
    "Gambia" to "Banjul",
    "Georgia" to "Tbilisi",
    "Germany" to "Berlin",
    "Ghana" to "Accra",
    "Greece" to "Athens",
    "Grenada" to "St. George's",
    "Guatemala" to "Guatemala City",
    "Guinea" to "Conakry",
    "Guinea-Bissau" to "Bissau",
    "Guyana" to "Georgetown",
    "Haiti" to "Port-au-Prince",
    "Honduras" to "Tegucigalpa",
    "Hungary" to "Budapest",
    "Iceland" to "Reykjavík",
    "India" to "New Delhi",
    "Indonesia" to "Jakarta",
    "Iran" to "Tehran",
    "Iraq" to "Baghdad",
    "Ireland" to "Dublin",
    "Israel" to "Jerusalem",
    "Italy" to "Rome",
    "Jamaica" to "Kingston",
    "Japan" to "Tokyo",
    "Jordan" to "Amman",
    "Kazakhstan" to "Nur-Sultan",
    "Kenya" to "Nairobi",
    "Kiribati" to "South Tarawa",
    "Korea, North" to "Pyongyang",
    "Korea, South" to "Seoul",
    "Kosovo" to "Pristina",
    "Kuwait" to "Kuwait City",
    "Kyrgyzstan" to "Bishkek",
    "Laos" to "Vientiane",
    "Latvia" to "Riga",
    "Lebanon" to "Beirut",
    "Lesotho" to "Maseru",
    "Liberia" to "Monrovia",
    "Libya" to "Tripoli",
    "Liechtenstein" to "Vaduz",
    "Lithuania" to "Vilnius",
    "Luxembourg" to "Luxembourg",
    "Madagascar" to "Antananarivo",
    "Malawi" to "Lilongwe",
    "Malaysia" to "Kuala Lumpur",
    "Maldives" to "Malé",
    "Mali" to "Bamako",
    "Malta" to "Valletta",
    "Marshall Islands" to "Majuro",
    "Mauritania" to "Nouakchott",
    "Mauritius" to "Port Louis",
    "Mexico" to "Mexico City",
    "Micronesia" to "Palikir",
    "Moldova" to "Chisinau",
    "Monaco" to "Monaco",
    "Mongolia" to "Ulaanbaatar",
    "Montenegro" to "Podgorica",
    "Morocco" to "Rabat",
    "Mozambique" to "Maputo",
    "Myanmar (formerly Burma)" to "Naypyidaw",
    "Namibia" to "Windhoek",
    "Nauru" to "Yaren",
    "Nepal" to "Kathmandu",
    "Netherlands" to "Amsterdam",
    "New Zealand" to "Wellington",
    "Nicaragua" to "Managua",
    "Niger" to "Niamey",
    "Nigeria" to "Abuja",
    "North Macedonia" to "Skopje",
    "Norway" to "Oslo",
    "Oman" to "Muscat",
    "Pakistan" to "Islamabad",
    "Palau" to "Ngerulmud",
    "Palestine State" to "Jerusalem",
    "Panama" to "Panama City",
    "Papua New Guinea" to "Port Moresby",
    "Paraguay" to "Asuncion",
    "Peru" to "Lima",
    "Philippines" to "Manila",
    "Poland" to "Warsaw",
    "Portugal" to "Lisbon",
    "Qatar" to "Doha",
    "Romania" to "Bucharest",
    "Russia" to "Moscow",
    "Rwanda" to "Kigali",
    "Saint Kitts and Nevis" to "Basseterre",
    "Saint Lucia" to "Castries",
    "Saint Vincent and the Grenadines" to "Kingstown",
    "Samoa" to "Apia",
    "San Marino" to "San Marino",
    "Sao Tome and Principe" to "Sao Tome",
    "Saudi Arabia" to "Riyadh",
    "Senegal" to "Dakar",
    "Serbia" to "Belgrade",
    "Seychelles" to "Victoria",
    "Sierra Leone" to "Freetown",
    "Singapore" to "Singapore",
    "Slovakia" to "Bratislava",
    "Slovenia" to "Ljubljana",
    "Solomon Islands" to "Honiara",
    "Somalia" to "Mogadishu",
    "South Africa" to "Pretoria",
    "South Sudan" to "Juba",
    "Spain" to "Madrid",
    "Sri Lanka" to "Colombo",
    "Sudan" to "Khartoum",
    "Suriname" to "Paramaribo",
    "Sweden" to "Stockholm",
    "Switzerland" to "Bern",
    "Syria" to "Damascus",
    "Taiwan" to "Taipei",
    "Tajikistan" to "Dushanbe",
    "Tanzania" to "Dodoma",
    "Thailand" to "Bangkok",
    "Timor-Leste" to "Dili",
    "Togo" to "Lome",
    "Tonga" to "Nuku'alofa",
    "Trinidad and Tobago",
    // Add more capital cities here
)



}
